global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets:
          - fastapi:8000

  - job_name: "kong"
    static_configs:
      - targets:
          - kong:8000
